name: Daily check workflow
on:
  pull_request:
  push:
    branches:
      - develop
      - master
  create:
    tags:
      - v*
env:
  CGO_ENABLED: 0
jobs: 
  dist:
    runs-on: ubuntu-latest
    name: Build image and publishes it
    env:
      COMMIT: ${{ github.sha }}
      VERSION: ${{ github.ref }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBLOGIN }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: xefiji/dailycheck
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}